api/urls.py
from django.urls import path  
from .import views 



app_name = 'blog'


urlpatterns = [
 path('',views.PostList.as_view(),name='postlist')
]

blog/urls.py
from django.urls import path  
from .import views 
from .feeds import LatestPostFeed
# from . views import PostListView


app_name = 'blog'


urlpatterns = [
  #post views  
  path('',views.post_list, name="post_list"),
  # path('',views.PostListView.as_view(), name="post_list"),
  path('detailt',views.detailt, name="detailt"),
  path('tag/<slug:tag_slug>', views.post_list,name='post_list_by_tag'),
  path('search/', views.post_search,name="post_search"),
  path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name="post_detail"),
  path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name="post_detail2"),
  path('<int:post_id>/share/', views.post_share,name="post_share"),
  path('feed/', LatestPostFeed(), name="post_feed"),


  ##
  path('list2',views.post_list2,name="post_list2"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap 
from blog.sitemaps import  PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace="blog")),
    path('',include('pages.urls',namespace="pages")),
    path('api/',include('api.urls')),

    path('sitemap.xml', sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User 
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
  def get_queryset(self): 
    return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
  STATUS_CHOICES = (
    ('draft','Draft'),
    ('published','Published'),

  )
  title = models.CharField(max_length=250)
  hot   = models.BooleanField(default=False)
  headline_post = models.BooleanField(default=False,null=True,)
  featured_post = models.BooleanField(default=False,null=True)
  slug  = models.SlugField(max_length=250, unique_for_date='publish')
  author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="blog_posts",)
  body = models.TextField()
  publish = models.DateTimeField(default=timezone.now)
  created = models.DateTimeField(auto_now_add=True)
  status  = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
  objects = models.Manager()
  published = PublishedManager()
  tags  = TaggableManager()


  class Meta:
    ordering = ('-publish'),

  def __str__(self):
    return self.title


  def get_absolute_url(self):
    return reverse('blog:post_detail', 
                  args=[self.publish.year,
                        self.publish.month, 
                        self.publish.day, 
                        self.slug
                  
                  ]
    )

  

class Comment(models.Model):
  post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
  name = models.CharField(max_length=80)
  email = models.EmailField()
  body = models.TextField()
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  active = models.BooleanField(default=True)


  class Meta:
    ordering = ('created',)

  def __str__(self):
    return f'comment by {self.name} on {self.post}'

blog/forms.py
from django import forms 
from .models import Comment
from crispy_forms.helper import FormHelper  
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Row, Column, Button
from crispy_forms.bootstrap import InlineRadios 



class EmailPostForm(forms.Form):

  name = forms.CharField(max_length=25, label = '', widget=forms.TextInput(attrs={'class':'form-control my-2','placeholder':'Name'}))
  email = forms.EmailField(max_length=25,label = '',widget=forms.EmailInput(attrs={'class':'form-control my-2','placeholder':'Email'}))
  to    = forms.EmailField(max_length=25, label='',widget=forms.EmailInput(attrs={'class':'form-control my-2','placeholder':'To'}))
  comments = forms.CharField(required=False, label="",widget=forms.Textarea(attrs={'class':'form-control my-2','placeholder':'comments (optional)'}))




  

  
   


class CommentForm(forms.ModelForm):

  name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Name'}))
  email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}))
  body  = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control mb-2','placeholder':'Body'}))
  
  class Meta:
    model = Comment 
    fields = ('name','email','body')

  
  




class SearchForm(forms.Form):
  query = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholoder':'Search'}))
  



  """   widgets = {
    'name' : forms.TextInput(attrs={'class':'form-control'}),
    
    'frequency' : forms.NumberInput(attrs={'class':'form-control'}),
 
    }
    
 def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.helper = FormHelper()
    self.fields['name'].label = "Name"
    self.fields['frequency'].label = 'Frequency'
   
    self.helper.form_method = 'post'
    self.helper.add_input(Submit('add_new_training_type','Add'))
    self.helper.layout = Layout(
      Row(
        Column('name'),
      ),
      Row(
        Column('frequency')
      )
    ) """

    

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 
from django.views.generic import ListView 
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail 
from taggit.models import Tag
from django.db.models import Count 
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from blog.models import Post 
from django.contrib import messages
from django.urls import reverse


# Create your views here.

def post_list2(request, tag_slug=None):
  object_list = Post.published.all()
  # tag_slug = None 
  tag = None
  if tag_slug:
    tag = get_object_or_404(Tag, slug=tag_slug)
    object_list = object_list.filter(tags__in=[tag])
  paginator = Paginator(object_list, 3)
  page = request.GET.get('page')
  try:
    posts = paginator.page(page)
  except PageNotAnInteger:
    posts = paginator.page(1)
  except EmptyPage:
    posts = paginator.page(paginator.num_pages)
  return render(request,'blog/post/list22.html',{'posts':posts,'page':page,'tage':tag})




def post_list(request, tag_slug=None):
  object_list = Post.published.all()
  hot_post    = Post.objects.filter(hot=True)
  # tag_slug = None 
  tag = None
  if tag_slug:
    tag = get_object_or_404(Tag, slug=tag_slug)
    object_list = object_list.filter(tags__in=[tag])
  paginator = Paginator(object_list, 12)
  page = request.GET.get('page')
  try:
    posts = paginator.page(page)
  except PageNotAnInteger:
    posts = paginator.page(1)
  except EmptyPage:
    posts = paginator.page(paginator.num_pages)
  return render(request,'blog/post/list.html',{'posts':posts,'page':page,'tage':tag,'hot_post':hot_post})
 
""" class PostListView(ListView):
  querysey = Post.published.all()
  context_object_name = 'posts'
  paginate_by = 3 
  template_name = 'blog/post/list.html' """

def post_detail(request, year, month, day, post):
  comment_form = CommentForm()
  post = get_object_or_404(Post, slug=post, status='published',publish__year=year, publish__month=month, publish__day=day)
  comments = post.comments.filter(active=True)
  new_comment = None
  if request.method == 'POST':
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
      new_comment = comment_form.save(commit=False)
      new_comment.post = post 
      new_comment.save()
      return redirect('blog:post_list')
      # return HttpResponseRedirect(reverse('blog:post_detail', args=[post]))
    
  else:
    comment_form = CommentForm()
    
  post_tags_ids = post.tags.values_list('id', flat=True)
  similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
  similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('same_tags','-publish')[:4]
  return render(request,'blog/post/detail.html',{'post':post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form,'similar_posts':similar_posts})


def detailt(request):

  return render(request,'blog/post/detail2.html')

def post_detail2(request, year, month, day, post):
  post = get_object_or_404(Post, slug=post, status='published',publish__year=year, publish__month=month, publish__day=day)
  comments = post.comments.filter(active=True)
  new_comment = None
  comment_form = CommentForm()
  if request.method == 'POST':
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
      comment_form.save(commit=False)
      comment_form.post = post 
      comment.save()
      return redirect('blog:post_list')
    else:
      comment_form = CommentForm()
  
  post_tags_ids = post.tags.values_list('id', flat=True)
  similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
  similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('same_tags','-publish')[:4]
  return render(request,'blog/post/detail.html',{'post':post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form,'similar_posts':similar_posts,'comment_form':comment_form,})




def post_share(request, post_id):

  post = get_object_or_404(Post, id=post_id,status='published')
  sent = False
  form = EmailPostForm()
      

  if request.method == 'POST':
    form = EmailPostForm(request.POST)
    if form.is_valid():
      cd = form.cleaned_data 
      post_url = request.build_absolute_uri(post.get_absolute_url ())
      subject = f"{ cd ['name']}" f"{post.title}"
      message = f"Read {post.title} at {post_url}\n\n"
      f"{cd['name']}\'s comments: {cd['comments']}"
      send_mail(subject, message, 'admin@a.com', [cd['to']])
      sent = True
      
  else: 
    form = EmailPostForm()
  return render(request, 'blog/post/share.html',{'post':post,'form':form,'sent':sent})
   

def post_search(request):
  form = SearchForm()
  query = None 
  results = []
  if 'query' in request.GET:
    form = SearchForm(request.GET)
    if form.is_valid():
      
      query = form.cleaned_data['query']
      search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
      search_query = SearchQuery(query)
      results = Post.published.annotate(
        search=search_vector,
        rank=SearchRank(search_vector, search_query)
      ).filter(rank__gte=0.3).order_by('-rank')
  return render(request,'blog/post/search.html',{'form':form,'query':query,'results':results})

templates/blog/base.html
{% load blog_tags %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

</head>


<body>

    <div id="content">
        {% block content %} {% endblock %}
    </div>

    <div id="sidebar">
        <h2>My Blog</h2>
        <p>This is my Blog i've written {% total_posts %} </p>
        <h3>Latest Posts</h3>
        {% show_latest_posts 3 %}

        <h3>Mosts commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href="{{post.get_absolute_url }}"> {{post.title}}</a>
            </li>

            {% endfor %}
        </ul>

        <p>
            <a href="{% url 'blog:post_feed' %}"> Subscribe to my RSS feed </a>
        </p>
    </div>

</body>

</html>

templates/blog/main.html
{% load blog_tags %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">

    <title>Hello, world!</title>
</head>

<body>

    <!--  Navbar -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/blog">Blog</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex" action="/blog/search" method="get">
                    <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search" required>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>


    {% block content %} this is the block {% endblock %}




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/blog/sidebar.html
{% load blog_tags %}
<div id="sidebar">
    <h2>My Blog</h2>
    <p>This is my Blog i've written {% total_posts %} post(s)</p>
    <h3>Latest Posts</h3>

    {% show_latest_posts 3 %}

    <h3>Mosts commented posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
        <li>
            <a href="{{post.get_absolute_url }}"> {{post.title}}</a>
        </li>

        {% endfor %}
    </ul>

    <p>
        <a href="{% url 'blog:post_feed' %}"> Subscribe to my RSS feed </a>
    </p>
</div>